=== AshIsAtWork/MolSim/src/fileHandling/reader/XMLHandling/Collision.xsd
<?xml version="1.0" encoding="utf-8"?>
<!-- Created with Liquid Technologies Online Tools 1.0 (https://www.liquid-technologies.com) -->
<xs:schema xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="Molecules">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Particles" type="xs:unsignedByte" />
                <xs:element name="OutputFileName" type="xs:string" />
                <xs:element name="TimeStep" type="xs:decimal" />
                <xs:element name="t_end" type="xs:unsignedShort" />
                <xs:element name="delta_t" type="xs:decimal" />
                <xs:element maxOccurs="unbounded" name="Cuboid">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Position">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="X" type="xs:decimal" />
                                        <xs:element name="Y" type="xs:decimal" />
                                        <xs:element name="Z" type="xs:decimal" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="N1" type="xs:unsignedByte" />
                            <xs:element name="N2" type="xs:unsignedByte" />
                            <xs:element name="N3" type="xs:unsignedByte" />
                            <xs:element name="Distance" type="xs:decimal" />
                            <xs:element name="Mass" type="xs:decimal" />
                            <xs:element name="Velocity">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="X" type="xs:decimal" />
                                        <xs:element name="Y" type="xs:decimal" />
                                        <xs:element name="Z" type="xs:decimal" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="Brownian" type="xs:decimal" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== AshIsAtWork/MolSim/input/assignment-3/2D-cuboid-collision.xml
<?xml version="1.0"?>

<!--

file      : cxx/tree/hello/hello.xml
copyright : not copyrighted - public domain

-->

<Molecules xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="../../src/fileHandling/reader/XMLHandling/Collision.xsd">
    <Particles>2</Particles>
    <OutputFileName>Collision2d</OutputFileName>
    <TimeStep>0.01</TimeStep>
    <t_end>1000</t_end>
    <delta_t>0.0002</delta_t>
    <Cuboid>
        <Position>
            <X>0.0</X>
            <Y>0.0</Y>
            <Z>0.0</Z>
        </Position>
        <N1>40</N1>
        <N2>8</N2>
        <N3>1</N3>
        <Distance>1.1225</Distance>
        <Mass>1.0</Mass>
        <Velocity>
            <X>0.0</X>
            <Y>0.0</Y>
            <Z>0.0</Z>
        </Velocity>
        <Brownian>0.1</Brownian>
    </Cuboid>
    <Cuboid>
        <Position>
            <X>15.0</X>
            <Y>15.0</Y>
            <Z>0.0</Z>
        </Position>
        <N1>8</N1>
        <N2>8</N2>
        <N3>1</N3>
        <Distance>1.1225</Distance>
        <Mass>1.0</Mass>
        <Velocity>
            <X>0.0</X>
            <Y>-10.0</Y>
            <Z>0.0</Z>
        </Velocity>
        <Brownian>0.1</Brownian>
    </Cuboid>
</Molecules>
